
services:    
  mysql:
    image: elestio/mysql:9.0
    container_name: mysql-container
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=test
      - MYSQL_PASSWORD=testp
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./etc/:/etc/mysql/conf.d
  apache:
    container_name: apache-container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./www/:/var/www/html
    expose:
      - 80
    ports:
      - 80:80
    links:
      - mysql
  pma:
    image: phpmyadmin
    links:
      - mysql
    ports:
      - 24581:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=test
      - PMA_PASSWORD=testp
      - UPLOAD_LIMIT=500M
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - mysql
